---
new_page_extension: md
auto_deploy: false
admin_path: static/content-admin
webhook_url: 
sections:
- type: directory
  path: content/video
  label: Videos
  create: documents
  match: "**/*"
  templates:
  - video
- type: directory
  path: content/event
  label: Event
  create: documents
  match: "**/*"
  templates:
  - event
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
  templates:
  - default
  - home
- type: directory
  path: content/about
  label: About
  create: all
  match: "**/*"
  templates:
  - default
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.54.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
version: '0.48'
